app_home:
  path: /
  controller: App\Controller\DefaultController::home

app_subscribe:
  path: /subscribe
  controller: App\Controller\SubscribeController::index

app_subscribe_success:
  path: /subscribe/success
  controller: App\Controller\SubscribeController::success

app_info:
  path: /info
  controller: App\Controller\DefaultController::info

app_index:
  path: /index
  controller: App\Controller\DefaultController::index