app_home:
  path: /
  controller: App\Controller\DefaultController::home

app_info:
  path: /info
  controller: App\Controller\DefaultController::info

app_index:
  path: /{_locale}/index
  controller: App\Controller\DefaultController::index

app_features:
  path: /features
  controller: App\Controller\DefaultController::features

app_contact:
  path: /contact
  controller: App\Controller\DefaultController::contact

admin:
  path: /admin
  controller: App\Controller\Admin\AdminController::admin
