controllers:
    resource: ../src/Controller/
    type: annotation

admin:
    path: /admin
    controller: App\Controller\AdminController::admin

kernel:
    resource: ../src/Kernel.php
    type: annotation